apiVersion: v1 
kind: Service 
metadata:   
  name: postgres-service   
  labels:     
    app: postgres 
spec:   
  type: NodePort   
  ports:    
    - port: 5454 
      nodePort: 30001   
  selector:    
    app: postgres 