apiVersion: v1 
kind: Service 
metadata:   
  name: mysql-service   
  labels:     
    app: mysql
spec:   
  type: NodePort   
  ports:    
    - port: 3306
      nodePort: 30001   
  selector:    
    app: mysql