apiVersion: v1 
kind: Service 
metadata: 
  name: veganbackend-service 
spec: 
  type: ClusterIP
  ports: 
   - protocol: TCP  
     port: 8085 
     targetPort: 8080 
  selector: 
    app: veganbackend
