apiVersion: v1 
kind: Service 
metadata: 
  name: veganfront-service 
spec: 
  type: NodePort
  ports: 
   - protocol: TCP  
     port: 8081
     targetPort: 80
     nodePort: 33010
  selector: 
    app: veganfront
